services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: jobboard-api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    env_file:
      - .env
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - jobboard.seq
      - jobboard.database
  
  jobboard.database:
    image: postgres:latest
    container_name: jobboard-database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jobboard.seq:
    image: datalust/seq:latest
    container_name: jobboard-seq
    ports:
      - "5341:5341"
      - "8081:80"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data: